name: Fetch Met Office Forecast
on:
  schedule:
    - cron: "47 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # install suitable python version

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run metoffice.py with 'place_code' parameter
        run: python metoffice.py gcpkmp259#

      - name: Commit any new SQL files generated
        run: |
          export TWOMONTHSAGO=$(date --date="$(date +%Y-%m-15) -2 month" +"%Y-%m")
          compgen -G *${TWOMONTHSAGO}-??.sql && tar -rf archive${TWOMONTHSAGO}.tar *${TWOMONTHSAGO}-??.sql --remove-files
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add forecasts/
          git commit -m "Add new SQL file"

      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
