name: Fetch Met Office Forecast
on:
  schedule:
    - cron: "47 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # install suitable python version

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run metoffice.py
        run: python metoffice.py gcpkmp259#

      - name: Commit any new SQL files generated
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -a forecasts/
          git commit -m "Add new SQL file"

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
