name: Update Met Office Forecast
on:
  schedule:
    - cron: "44 04-20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # install suitable python version
          
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: install python packages
        run: uv --system pip install -r requirements.txt

      - name: execute py script # run metoffice_update.py with 'place_code' parameter
        run: python metoffice_update.py gcpkmp259#

      - name: Commit any new SQL files generated
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add forecasts/
          test -z "$(git status --porcelain forecasts/)" || git commit -m "Update SQL forecast file, $(date)"

      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
